version: '3'
services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.14.2
    ports:
      - 5400:5400
    command: mlflow ui --port 5400 --backend-store-uri sqlite:///data/mlflow.db --artifacts-destination /mlartifacts --serve-artifacts --host 0.0.0.0
    volumes:
      - ./data/mlflow/data:/data
      - ./data/mlflow/mlartifacts:/mlartifacts
